name: Welcome New Contributor

on:
  pull_request_target:
    types: [opened]

jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting message
        uses: actions/first-interaction@v1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thanks for your first issue!"
          pr-message: "🎉 Thanks for your first pull request!"